### ISSUE TITLE
Icos of different size and color for selected and not selected items.

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#15]
Hello,

Is it possible with this framework to do something similar to what is below in gif?
And also make paging menu scroll horizontally to the left/ right margins? Currently it's not scrolled but rather move to the next (left/ right) item.
![example](https://cloud.githubusercontent.com/assets/16180201/21243629/f6faee82-c319-11e6-913c-e48a4f60b19d.gif)

**Comment by rechsteiner** [comment]
Hey. So sorry for the late response! This isn't really possible at the moment, but I'm working on an update that will fix these issues. I've broken them into three separate issues:

- #17 Add progress value to menu items
- #18 Scroll menu items alongside content
- #19 Allow scrolling in the menu header

When these are fixed it should be trivial do get the behaviour you want. You basically need to create your own `PagingCell` subclass that contains an image view, and updates the size and `tintColor` based on the a `progress` value  (working on adding the `progress ` value in #17).

I'll let you know when it's ready!

**Comment by IVANKRUPSKI** [comment]
Great!
I am thankful for that.

**Comment by rechsteiner** [comment]
Sorry, closed the wrong issue!

**Comment by rechsteiner** [comment]
Alright, #17 and #18 should be done now. I've added a new example project called `IconsExample` that implements pretty much the same behaviour as you described.

Scrolling in the header is still not completed, but you can enable it yourself by setting this:

```Swift
pagingViewController.collectionView.isScrollEnabled = true
pagingViewController.collectionView.showsHorizontalScrollIndicator = false
```

This should work perfectly fine if you don't have too many elements. The problem with having a lot of menu items is that the collection view (which is how the menu items are implemented) only displays the necessary items to cover the screen. In order to properly support scrolling in the header we need to reload the data in the collection view as you're scrolling. I'm going to try to get that working pretty soon, but the solution above might work fine for your use case.

**Comment by IVANKRUPSKI** [comment]
Hey!

Thank you very much for this upgrade. It's very much appreciated.

Shall I close it, or you want to finish #19 first?

P.S.There is another small issue, but I will create separate case for it.

**Comment by rechsteiner** [comment]
Awesome! You can just leave it open for now. I'm quite close to completing the scrolling issue as well–just some minor tweaks left.

**Comment by rechsteiner** [comment]
Turns out adding scrolling to the menu items was much more complicated than I originally thought. I'm getting quite close, but there is still a bunch of small issues I need to fix. I'm just going to close this in order to clean up the issues a bit, but I will let you know in #19 when it's ready ✌️
