### ISSUE TITLE
how to resize paging item when scroll like new update in Instagram ?

### ISSUE THREAD

**Issue by MinaThabet1** [rechsteiner/Parchment#218]

**Comment by rechsteiner** [comment]
Hi @MinaThabet1! I'm not sure I understand exactly what you mean. Could you describe what you're trying to achieve a bit more? 🙂

**Comment by Smiller193** [comment]
yeah I think he means that when you scroll down the paging item shrinks

**Comment by MinaThabet1** [comment]
Yes, that's exactly what I meant.

**Comment by rechsteiner** [comment]
I've updated the Unplash example to show how you can achieve this: https://github.com/rechsteiner/Parchment/blob/master/UnplashExample/ViewController.swift

Here's a video of how it looks like: https://www.youtube.com/watch?v=WMgfVHYGJe0

Note: I found a bug with the way the collection view layout was invalidated that I needed to fix in order to get this working: #240. I will try to get a new version release soon, but in the meantime you have to target the `master` branch to get this working.

**Comment by MinaThabet1** [comment]
Ok thank you so much

**Comment by rechsteiner** [comment]
No problem! Let me know if you find any issues with that implementation 🙂
