### ISSUE TITLE
Can't find a Custom "menuLayoutClass"  demo

### ISSUE THREAD

**Issue by michaeldong** [rechsteiner/Parchment#248]
In PagingViewControllerLayout.swift file, you write this comment:  

```
To create your own `PagingViewControllerLayout` you need to override the `menuLayoutClass` property on `PagingViewController`.
Then you can override the methods you normally would to update the  layout attributes for each cell.
```

I want to implement my own menuLayout.   For Example: vertical's flow layout or other layout I need. 

Solution1:
Through your comment. I  must subclass  PagingViewControllerLayout directly. 
I have try subclass it , override it's prepare() function, but I can't override PagingViewControllerLayout's  func "createLayoutAttributes", because it is private.

Solution2:
Or  directly subclass UICollectionViewLayout like PagingViewControllerLayout? but menuLayouClass's property is PagingViewControllerLayout type. When init PagingViewController
pagingViewController.menuLayoutClass = CustomLayout.self , CustomLayout must PagingViewControllerLayout's subclass?  

I can't find a Demo in your Examples projects for this issue.   
Search all issues about "custom menulayout".  but I can't find a good demo or UnitTest for this?
what should I do to implement a custom menuLayout.  Thanks.

Thank you again for your great project, Hope your reply.

**Comment by rechsteiner** [comment]
Hi @michaeldong! Yeah, the documentation for custom layouts is very lacking. I'll try to improve that when I have some more time 🙂

It's true that need to subclass `PagingViewControllerLayout` and not `UICollectionViewLayout`. You basically need to override the same methods that you would if you where subclassing `UICollectionViewFlowLayout`, e.g. `layoutAttributesForElements(in rect:)` and `layoutAttributesForItem(at indexPath:)`. There you can modify the layout attributes to return your custom behaviour. That means it's a bit limited what you can customize, as that you are kind of "stuck" with what is returned from `createLayoutAttributes`.

I think it would be very cool if you could create completely custom layouts, but it's a bit tricky to find a generic solution that works well with the distance calculations that are needed in order to update the content offset while scrolling.

Here is a simple example of a custom layout that rotates all the items in the menu:

```Swift
class CustomPagingCollectionViewLayout: PagingCollectionViewLayout<ImageItem> {
  
  override func shouldInvalidateLayout(forBoundsChange newBounds: CGRect) -> Bool {
    return true
  }
  
  override func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
    guard let layoutAttributes = super.layoutAttributesForElements(in: rect) else { return nil }
    
    for attributes in layoutAttributes {
      if attributes.representedElementCategory == .cell {
        attributes.transform = CGAffineTransform(rotationAngle: 0.5)
      }
    }
    
    return layoutAttributes
  }
  
  override func layoutAttributesForItem(at indexPath: IndexPath) -> UICollectionViewLayoutAttributes? {
    guard let attributes = super.layoutAttributesForItem(at: indexPath) else { return nil }
    if attributes.representedElementCategory == .cell {
      attributes.transform = CGAffineTransform(rotationAngle: 0.5)
    }
    return attributes
  }
  
}
```

**Comment by michaeldong** [comment]
@Rechsteiner. Thank you for your detail reply and your demo code. I think your reply solve my question of subclass which class 「PagingViewControllerLayout」.

Next, I will base your 「rotationAngle」code. Try  to solve my problem :「 Left is custom Menu ，Right is pages, pages can up-down scroll.」
Your current demo: Top is menu layout, Bottom is pages, pages can scroll left-right.
I don't want to change menu styles because it's good enough for me. I only want to let menu from horizon to vertical ，pages scroll up-down.

Thank again for you again, Good luck!

**Comment by michaeldong** [comment]
wow, Parchment May support vertical or generic layout in future.  Thank you for you and your parchment again. Your sincere reply save me much time! Thanks.
