### ISSUE TITLE
Different width for a selected cell

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#25]
Do you think it's possible to have different width for a selected cell?

And update it (width) dynamically (with animation) moving from current to the next cell.

**Comment by rechsteiner** [comment]
This isn't possible at the moment, but it shouldn't be that difficult to get this working. We probably need to add some `progress` value to the `widthForPagingItem pagingItem:` delegate method, so that we can return different a width based on how far you've scrolled.

**Comment by IVANKRUPSKI** [comment]
Ok. Understood. 

Would be great to have it in the next update.
Thank you!

**Comment by miguelalvescosta** [comment]
Hi, and if possible different background menu color on each menu tab?

**Comment by rechsteiner** [comment]
@miguelalvescosta could you open a separate issue with a bit more details on what you're trying to achieve? Do you want the background color to change based on which item is selected or do you want each cell to always have a specific color? Both should be possible with the current version 🙂

**Comment by rechsteiner** [comment]
Finally got this working now!

The `widthForPagingItem` delegate method now has a `isSelected` argument that you can use to return a different width for the selected cell. You can check out the `DelegateExample` target for more details. Here's the PR: #85 

And sorry for taking so long – it turned out to be much harder than I originally thought.  Will release a new version pretty soon ✌️

**Comment by IVANKRUPSKI** [comment]
Cool!
Looking forward to seeing that working.
