### ISSUE TITLE
Setting title at viewDidLoad issue

### ISSUE THREAD

**Issue by igordeoliveirasa** [rechsteiner/Parchment#250]
If I set the title of my viewControllers at viewDidLoad, Tabs dont show anything.

**Comment by rechsteiner** [comment]
Hi! Yes, this is because it's reading the `title` property of the view controllers when you initialize your `PagingViewController`. It's not observing changes to the title property, so if you set the title after you initialize your `PagingViewController` it will not show anything. You either need to set the title properties earlier (e.g. in init), or call `reloadData` after you updated your titles 🙂

**Comment by michael-pont** [comment]
Thank you @rechsteiner, the above comment helped me.
Had the title property in required init and not in override init which caused the titles not to show in the menu. The following code works for me:

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        title = "Challenge"
    }
