### ISSUE TITLE
Wrong index when selecting menu item

### ISSUE THREAD

**Issue by Smiller193** [rechsteiner/Parchment#332]
I am following the unsplash example to create my primary UI. I have four items/indexes which help me differentiate what data that I want to pull. For some reason when I click a menu item lets say the one In the first index ( 0 th) it loads the content in the 2nd index ( 1st due to the fact that it is array based) should be loading content for a view controller that isn't present yet. Also when I switch between view controllers all the data seems to be reloaded. Is that usual behavior?

**Comment by rechsteiner** [comment]
Hi @Smiller193! I'm struggling to reproduce this. Are you able to reproduce this in one of the example targets as well?

**Comment by khoogheem** [comment]
interesting.. we have seen this too.. just have not had enough time to debug why

**Comment by rechsteiner** [comment]
@Smiller193 any updates on this?

**Comment by Jorge-Palomino** [comment]
Same things happens to me. I'm in the fourth tab, select the first and it loads the content on the second index, then if you try to swipe to another index the order of the content is wrong and menu selecting item says it's not the one I've selected. Swiping between controllers has a smooth animation, but selecting an index takes a lot of time because I think it loads the VC between current and new selected index.
