### ISSUE TITLE
Gradient menu background

### ISSUE THREAD

**Issue by Silvia4** [rechsteiner/Parchment#365]
Hi,
thanks for your work. 
I'm trying to use a gradient for the menu (from left to right). I've put everything transparent and then added a gradient sublayer, but it doesn't show.

`pagingViewController.backgroundColor = UIColor.clear
pagingViewController.menuBackgroundColor = UIColor.clear
pagingViewController.collectionView.backgroundColor = UIColor.clear
pagingViewController.view.backgroundColor = UIColor.clear`

`let gradientLayer = CAGradientLayer()
gradientLayer.frame = pagingViewController.view.bounds
gradientLayer.colors = [UIColor.blue, UIColor.green]
gradientLayer.startPoint = CGPoint(x: 0.0, y: 0.5)
gradientLayer.endPoint = CGPoint(x: 1.0, y: 0.5)
pagingViewController.view.layer.addSublayer(gradientLayer)`

Can you please help me? 
Thanks!

**Comment by rechsteiner** [comment]
Hi @Silvia4! There a couple of issues with your implementation: 

- You need to use .cgColor in `gradientLayer.colors`. E.g: `[UIColor.blue.cgColor, UIColor.green.cgColor]` 
- You probably want to add the layer `pagingViewController.collectionView` instead of the entire paging view. You should also do `.insertSublayer(gradientLayer, at: 0)` instead to insert the view at the bottom of the view hierarchy.
- You need to set the frame of the layer when the frame of the collection view is not zero. E.g. `viewDidLayoutSubviews` or `viewWillAppear`. 

That should do it 🙂
