### ISSUE TITLE
Menu items (at least in the IconsExample) appear with slight delay when segue -> present modally

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#43]
![ezgif-1-305e6aaf58](https://cloud.githubusercontent.com/assets/16180201/24247627/beddd1d6-0fcc-11e7-8358-c3c9c4f12371.gif)

**Comment by IVANKRUPSKI** [comment]
Hey there!
No ideas so far why this happens? I would really appreciate your help.

**Comment by rechsteiner** [comment]
Hi! Sorry for the late response 🙌 This is probably happening because I'm calculating the menu items in `viewDidAppear`, which is trigged too late and causes that delay you're seeing. I'm pretty sure it should work to just move the rendring into `viewDidLayoutSubviews`. I'll take a look at tomorrow and see if I can get a fix out ✌️

**Comment by IVANKRUPSKI** [comment]
Thank you!

**Comment by rechsteiner** [comment]
Should be fixed in #45

**Comment by IVANKRUPSKI** [comment]
Yes, it's fixed.
Thank you, much appreciated.
