### ISSUE TITLE
IBoutlet Key not Coding-Compliant for the Key in PagingCell?

### ISSUE THREAD

**Issue by YanwuX** [rechsteiner/Parchment#457]
I am using an xib for the menu cell and I have successfully set up parchment and it works just fine without connecting the IBoutlets.
However, when I connect the xib to an @IBoutlet, I have " Key Value Coding-Compliant for the Key exception".

I have double-checked the IBoutlet name and the connection name and file owner. everything seems just fine. and I am not able to find the possible cause for this issue.

![image](https://user-images.githubusercontent.com/9937454/77504240-c35ea480-6e9a-11ea-9a81-f38af0d2a7a2.png)

I am using IBoutlets in other classes as well, but only when I connect the menu IBoutlets, I got errors.

Anyone has encountered similar issues?

**Comment by rechsteiner** [comment]
Hi @YanwuX! Looks like you might have setup the outlets incorrectly. Try setting the outlets on the PagingCell subclass instead of the File's Owner:

<img width="411" alt="Screenshot 2020-03-26 at 20 37 38" src="https://user-images.githubusercontent.com/1238984/77689335-ca240f00-6fa1-11ea-8203-72a83516901f.png">

**Comment by YanwuX** [comment]
Thanks so much, I have connected it to the view and everything works
