### ISSUE TITLE
min iOS version

### ISSUE THREAD

**Issue by JeromeCHA** [rechsteiner/Parchment#70]
I was wondering, why does this pod min iOS version is 8.2? I think 8.0 should be fine.
If it is possible, to have the min iOS version set to 8.0 please?

**Comment by rechsteiner** [comment]
Hi!

It was done because of a bug in `UICollectionView` that got fixed in version 8.2. I can't remember exactly what the bug was, but it would require some work to reliably change to min version to 8.0. According to [this](https://david-smith.org/iosversionstats/) the usage percentage for 8.x is just 0.9%, so I'm tempted to just leave this as it is.
