### ISSUE TITLE
Menu on navigationbar

### ISSUE THREAD

**Issue by qiaqiaxian** [rechsteiner/Parchment#93]
Hi,i want to add menu on navigationbar , how to work it out.
Or Parchment can't do it like that? 
I'll be waiting for your reply.

**Comment by rechsteiner** [comment]
Yeah this is definitely possible!

You basically need to move the `collectionView` into the navigation bar by setting the `titleView` property on the `navigationItem`, like this:

```Swift
navigationItem.titleView = pagingViewController.collectionView
```

Then you need to set the frame of the title view. For example, if you always want it to be the same size as the navigation bar:

```Swift
override func viewDidLayoutSubviews() {
  guard let navigationBar = navigationController?.navigationBar else { return } 
  navigationItem.titleView?.frame = CGRect(origin: .zero, size: navigationBar.bounds.size)
}
```

You also need to update constraints of the `PagingView`, as the default implementation will setup some auto-layout constraints that will mess the collection view. Since you're putting the menu view inside the navigation bar we basically want to remove the layout constraints for the menu view and set the page view controller to extend the entire size. To do this you need to create you own `PagingView` subclass, and override `setupConstraints`:

```Swift
class CustomPagingView: PagingView {
  override func setupConstraints() {
    pageView.translatesAutoresizingMaskIntoConstraints = false
    pageView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
    pageView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true
    pageView.topAnchor.constraint(equalTo: topAnchor).isActive = true
    pageView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
  }
}
```

Then create your own `PagingViewController` subclass and set your custom view:

```Swift
class CustomPagingViewController: FixedPagingViewController {
  override func loadView() {
    view = CustomPagingView(
      pageView: pageViewController.view,
      collectionView: collectionView,
      options: options)
  }
}
```

I've also added a new [navigation bar example](https://github.com/rechsteiner/Parchment/blob/master/NavigationBarExample/ViewController.swift) you can take look at for the full implementation. Hope this works for you!

**Comment by qiaqiaxian** [comment]
Thanks! It's very helpful.
I've solved my problem.
Thank you again.
